-- --------------------------------------------------------
-- Хост:                         172.16.0.248\bstusqlserver
-- Версия сервера:               Microsoft SQL Server 2019 (RTM) - 15.0.2000.5
-- Операционная система:         Windows Server 2019 Standard 10.0 <X64> (Build 17763: )
-- HeidiSQL Версия:              12.0.0.6468
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES  */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Дамп структуры для таблица Students.StudentHistory
CREATE TABLE IF NOT EXISTS "StudentHistory" (
	"IdMove" NUMERIC(18,0) NOT NULL,
	"IdStud" NUMERIC(18,0) NOT NULL,
	"IdMoveType" NUMERIC(18,0) NOT NULL,
	"DateMove" SMALLDATETIME NOT NULL,
	"IdStatus" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdF" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdForma" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdEduType" NUMERIC(18,0) NULL DEFAULT NULL,
	"IsForeign" TINYINT NULL DEFAULT NULL,
	"IdKurs" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdPP" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdGroup" NUMERIC(18,0) NULL DEFAULT NULL,
	"VUZ" VARCHAR(255) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_F" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Notes" VARCHAR(255) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"BDateVac" SMALLDATETIME NULL DEFAULT NULL,
	"EDateVac" SMALLDATETIME NULL DEFAULT NULL,
	"IdReason" NUMERIC(18,0) NULL DEFAULT NULL,
	"BDateZan" SMALLDATETIME NULL DEFAULT NULL,
	"IdOrd" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdApp" NUMERIC(18,0) NULL DEFAULT NULL,
	"UserName" VARCHAR(128) NULL DEFAULT '' COLLATE 'Cyrillic_General_CI_AS',
	"rowguid" UNIQUEIDENTIFIER NOT NULL,
	"YearScPlan" SMALLINT NULL DEFAULT NULL,
	"IdTypeStudent" NUMERIC(18,0) NULL DEFAULT NULL,
	"EduDateB" SMALLDATETIME NULL DEFAULT NULL,
	"EduDateE" SMALLDATETIME NULL DEFAULT NULL,
	"IdDecl" NUMERIC(18,0) NULL DEFAULT NULL,
	"DateMoveServer" DATETIME NULL DEFAULT '',
	"IdVac" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdDogovor" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdMoveTypeSub" NUMERIC(18,0) NULL DEFAULT NULL,
	"Name_F_R" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_F_D" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_F_V" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_F_T" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_F_P" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I_R" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I_D" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I_V" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I_T" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_I_P" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O_R" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O_D" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O_V" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O_T" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Name_O_P" VARCHAR(50) NULL DEFAULT NULL COLLATE 'Cyrillic_General_CI_AS',
	"Pol" BIT NULL DEFAULT NULL,
	"IsVacFreeStudy" BIT NULL DEFAULT NULL,
	"IdFormaStep" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdDiscount" NUMERIC(18,0) NULL DEFAULT NULL,
	"IdOrdToCancel" NUMERIC(18,0) NULL DEFAULT NULL,
	"DateMoveIsEqualToDateOrd" BIT NULL DEFAULT NULL,
	"IdKafedra" NUMERIC(18,0) NULL DEFAULT NULL,
	FOREIGN KEY INDEX "FK_OK_Move_OK_MoveType" ("IdMoveType"),
	FOREIGN KEY INDEX "FK_StudentHistory_EduType" ("IdEduType"),
	FOREIGN KEY INDEX "FK_StudentHistory_Foreign" ("IsForeign"),
	FOREIGN KEY INDEX "FK_StudentHistory_FormaStep" ("IdFormaStep"),
	FOREIGN KEY INDEX "FK_StudentHistory_O_Orders" ("IdOrd"),
	FOREIGN KEY INDEX "FK_StudentHistory_O_OrdersToCancel" ("IdOrdToCancel"),
	FOREIGN KEY INDEX "FK_StudentHistory_OK_MoveTypeSub" ("IdMoveTypeSub"),
	FOREIGN KEY INDEX "FK_StudentHistory_p_Discount" ("IdDiscount"),
	FOREIGN KEY INDEX "FK_StudentHistory_p_Dogovor" ("IdDogovor"),
	FOREIGN KEY INDEX "FK_StudentHistory_StudentDeclare" ("IdDecl"),
	FOREIGN KEY INDEX "FK_StudentHistory_VacStudent" ("IdVac"),
	PRIMARY KEY ("IdMove"),
	CONSTRAINT "FK_OK_Move_OK_MoveType" FOREIGN KEY ("IdMoveType") REFERENCES "OK_MoveType" ("IdMoveType") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_EduType" FOREIGN KEY ("IdEduType") REFERENCES "EduType" ("IdEduType") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_Foreign" FOREIGN KEY ("IsForeign") REFERENCES "Foreign" ("IsForeign") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_FormaStep" FOREIGN KEY ("IdFormaStep") REFERENCES "FormaStep" ("IdFormaStep") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_O_Orders" FOREIGN KEY ("IdOrd") REFERENCES "O_Orders" ("IdOrd") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_O_OrdersToCancel" FOREIGN KEY ("IdOrdToCancel") REFERENCES "O_Orders" ("IdOrd") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_OK_MoveTypeSub" FOREIGN KEY ("IdMoveTypeSub") REFERENCES "OK_MoveTypeSub" ("IdMoveTypeSub") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_p_Discount" FOREIGN KEY ("IdDiscount") REFERENCES "p_Discount" ("IdDiscount") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_StudentDeclare" FOREIGN KEY ("IdDecl") REFERENCES "StudentDeclare" ("idDecl") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_VacStudent" FOREIGN KEY ("IdVac") REFERENCES "VacStudent" ("IdVac") ON UPDATE NO_ACTION ON DELETE NO_ACTION,
	CONSTRAINT "FK_StudentHistory_p_Dogovor" FOREIGN KEY ("IdDogovor") REFERENCES "p_Dogovor" ("IdDogovor") ON UPDATE NO_ACTION ON DELETE NO_ACTION
);

-- Экспортируемые данные не выделены.

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
